default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ThoughtStream_development

test:
  <<: *default
  database: ThoughtStream_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
